### ISSUE TITLE
Upgrade kubeflow gcp stack to v1.5.0

### ISSUE THREAD

**Issue by akranga** [epam/ai-stacks#3]
Upgrade a Kubeflow stack to version v1.5.0 and use it as a reference. Use [manifests-v1.5.0](https://github.com/kubeflow/manifests/tree/v1.5.0) as a kustomize base

- [x] agilestacks/kubeflow-components#1
- [x] agilestacks/kubeflow-components#16
- [x] agilestacks/kubeflow-components#7
- [x] agilestacks/kubeflow-components#3
- [ ] agilestacks/kubeflow-components#22
- [x] agilestacks/kubeflow-components#19
- [x] agilestacks/kubeflow-components#17
- [x] agilestacks/kubeflow-components#21
- [x] Upgrade Central Dashboard
- [x] agilestacks/kubeflow-components#8
- [x] agilestacks/kubeflow-components#9
- [x] Add agilestacks/kubeflow-components#6 (done as part of research)
- [ ] Add agilestacks/kubeflow-components#10
